Update default tempest tag to Oct 2018
Let's update the default's tempest tag one month more so that
tempest contains follow_redirects parameter [1] in its RestClient
needed to run dns add-on tests. Without the change some of the
designate_tempest_plugin tests were failing with TypeError:
__init__() got an unexpected keyword argument 'follow_redirects'

[1] https://review.opendev.org/c/openstack/tempest/+/580146

Change-Id: I5fde40ff2ed3e6e258a18ba431ab9aef2009c891