Fix load() missing argument Loader
This patch replace yaml.load() by yaml.safe_load() which will
fix the TypeError our jobs currently face:
TypeError: load() missing 1 required positional argument: 'Loader'

Change-Id: I3d238eabf374be895782ebc9e4907db93157a5d4